name: 'generate-lxc'
on:
  pull_request:
  push:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: workflow/nix-shell-action@v3
        with:
          packages: nixos-generators
          script: |
            nixos-generate -f proxmox-lxc -c ./configuration.nix
