name: 'generate-lxc'

# build only on new version tags with hostname suffix
on:
  push:
    tags:
      - 'v*.*.*-*'

# softprops/action-gh-release@v1 needs these permissions
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract hostname
        run: echo "HOSTNAME=${GITHUB_REF#refs/tags/*-}" >> $GITHUB_ENV

      - name: Install nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate NixOS configuration
        # run generator from flake with the configuration specified by the hostname
        run: |
          nix run github:nix-community/nixos-generators -- -f proxmox-lxc --flake .#${{ env.HOSTNAME }} | {
            read path
            echo "BUILD_PATH=$path" >> $GITHUB_ENV
          }

      - name: Prepend hostname to file name
        # Copy to working directory because we don't have permissions to change the file name in /nix/store
        run: |
          NEW_FILENAME="${{ env.HOSTNAME }}-$(basename ${{ env.BUILD_PATH }})"
          RELEASE_PATH="${{ github.workspace }}/$NEW_FILENAME"
          cp "${{ env.BUILD_PATH }}" "$RELEASE_PATH"
          echo "RELEASE_PATH=$RELEASE_PATH" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.RELEASE_PATH }}
